### ISSUE TITLE
Getting audio from docker container

### ISSUE THREAD

**Issue by jhairssteven** [kiwicampus/Integration-Engineer-Test-2024#3]
Hi, I encountered an issue with playing audio in the Docker container and getting the sound to play on the host system. I’ve already resolved the problem and it’s working now. However, from the [troubleshooting](https://github.com/kiwicampus/Integration-Engineer-Test-2024/blob/main/docs/running_dev_container.md#troubleshooting) section, it’s unclear to me whether the audio fix should be pushed to the repository.

Is it expected to submit a solution for this issue as part of the test? If not, I can create a pull request to add the fix to the repository and make the solution to this issue available to others.

Thanks.

**Comment by salogranada** [comment]
Hi Jhair, we have confirmed the issue! Thanks for noticing!
Please make the PR on this repository. Remember to add detailed testing steps. 

You already have points for identifying and reporting the issue. You will get more points if your PR works, but this is a one-shot! So, test your solution thoroughly. If it doesn't work, we will upload the solution so others can work with it.
